version: 2

sources:
  - name: raw_trip_data
    database: dbt
    schema: raw_data
    tables:
      - name: green_taxi_trips_jan2025
        description: > 
          Trip-level data for green taxis in New York City for January 2025.
          Green taxis, also known as boro taxis or street-hail liveries, were introduced in August 2013
          to improve taxi service in the outer boroughs and northern Manhattan. They operate similarly to yellow taxis,
          and the dataset includes fields such as pickup and dropoff timestamps, trip distance, fare, tip amount, and location IDs.
          
        columns:
        - name: vendor_id
          description: >
            A code indicating the LPEP provider that provided the record.
            1 = Creative Mobile Technologies, LLC
            2 = Curb Mobility, LLC
            6 = Myle Technologies Inc

        - name: PULocationID
          description: >
            TLC Taxi Zone in which the taximeter was engaged

        - name: DOLocationID
          description: >
            TLC Taxi Zone in which the taximeter was disengaged.

        - name: lpep_pickup_datetime
          description: >
            The date and time when the meter was engaged.

        - name: lpep_dropoff_datetime
          description: >
            The date and time when the meter was disengaged

        - name: passenger_count
          description: >
            The number of passengers in the vehicle. 

        - name: trip_distance
          description: >
            The elapsed trip distance in miles reported by the taximeter.

        - name: pickup_longitude
          description: >
            Longitude coordinate where the trip started.

        - name: pickup_latitude
          description: >
            Latitude coordinate where the trip started.

        - name: rate_code_id
          description: >
            The final rate code in effect at the end of the trip.
            1 = Standard rate
            2 = JFK
            3 = Newark
            4 = Nassau or Westchester
            5 = Negotiated fare
            6 = Group ride
            99 = Null/unknown


        - name: store_and_fwd_flag
          description: >
            This flag indicates whether the trip record was held in vehicle memory before
            sending to the vendor, aka “store and forward,” because the vehicle did not
            have a connection to the server.

        - name: dropoff_longitude
          description: >
            Longitude coordinate where the trip ended.

        - name: dropoff_latitude
          description: >
            Latitude coordinate where the trip ended.

        - name: payment_type
          description: >
            A numeric code signifying how the passenger paid for the trip.
            0 = Flex Fare trip
            1 = Credit card
            2 = Cash
            3 = No charge
            4 = Dispute
            5 = Unknown
            6 = Voided trip

        - name: fare_amount
          description: >
            The time-and-distance fare calculated by the meter.

        - name: extra
          description: >
            Miscellaneous extras and surcharges.

        - name: mta_tax
          description: >
            Tax that is automatically triggered based on the metered rate in use

        - name: improvement_surcharge
          description: >
            Improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015.

        - name: tip_amount
          description: >
            Tip amount – This field is automatically populated for credit card tips. Cash tips are not included.

        - name: tolls_amount
          description: >
            Total amount of all tolls paid in trip.

        - name: total_amount
          description: >
            The total amount charged to passengers. Does not include cash tips.

        - name: trip_type
          description: >
            A code indicating whether the trip was a street-hail or a dispatch that is
            automatically assigned based on the metered rate in use but can be altered
            by the driver.
            1 = Street-hail
            2 = Dispatch

        - name: congestion_surcharge
          description: >
            Total amount collected in trip for NYS congestion surcharge.

        - name: cbd_congestion_fee
          description: >
            Per-trip charge for MTA's Congestion Relief Zone starting Jan. 5, 2025.
